# Generated by Django 5.2 on 2026-05-26 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('product_type', models.CharField(choices=[('product', 'Товар'), ('service', 'Услуга')], default='product', max_length=10, verbose_name='Тип')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('monument_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длина (см)')),
                ('monument_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина (см)')),
                ('monument_thickness', models.PositiveIntegerField(blank=True, null=True, verbose_name='Толщина (см)')),
                ('material', models.CharField(blank=True, choices=[('granite', 'Гранит'), ('marble', 'Мрамор'), ('gabbro', 'Габбро'), ('other', 'Другое')], max_length=20, null=True, verbose_name='Материал')),
                ('tile_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длина плитки (см)')),
                ('tile_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина плитки (см)')),
                ('coating_type', models.CharField(blank=True, choices=[('polished', 'Полированная'), ('matt', 'Матовая'), ('thermo', 'Термообработка'), ('bush', 'Бучардированная')], max_length=20, null=True, verbose_name='Тип покрытия')),
                ('tiles_per_pack', models.PositiveIntegerField(blank=True, null=True, verbose_name='Штук в упаковке')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='goods.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар/Услуга',
                'verbose_name_plural': 'Товары и услуги',
                'ordering': ['-is_popular', 'name'],
            },
        ),
    ]
