# Generated by Django 5.2 on 2026-05-27 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (₽)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('product_type', models.CharField(choices=[('product', 'Товар'), ('service', 'Услуга')], default='product', max_length=10, verbose_name='Тип')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный')),
                ('length_p', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Длина (см)')),
                ('width_p', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Ширина (см)')),
                ('thickness_p', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Толщина (см)')),
                ('material', models.CharField(blank=True, choices=[('granite', 'Гранит'), ('marble', 'Мрамор'), ('limestone', 'Известняк'), ('composite', 'Композит'), ('other', 'Другое')], max_length=20, verbose_name='Материал')),
                ('tile_length', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Длина плитки (см)')),
                ('tile_width', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Ширина плитки (см)')),
                ('tile_thickness', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Толщина (мм)')),
                ('coating_type', models.CharField(blank=True, choices=[('polished', 'Полированная'), ('matte', 'Матовая'), ('brushed', 'Брашированная'), ('thermal', 'Термообработанная'), ('natural', 'Натуральная')], max_length=30, verbose_name='Тип покрытия')),
                ('quantity_per_pack', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество в упаковке (шт)')),
                ('service_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок выполнения (дни)')),
                ('service_notes', models.TextField(blank=True, verbose_name='Особенности услуги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='goods.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар/Услуга',
                'verbose_name_plural': 'Товары и услуги',
                'ordering': ['name'],
            },
        ),
    ]
