# Generated by Django 6.0.5 on 2026-05-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='monument_length',
            field=models.PositiveIntegerField(blank=True, help_text='Для памятников', null=True, verbose_name='Длина (см)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='monument_thickness',
            field=models.PositiveIntegerField(blank=True, help_text='Для памятников', null=True, verbose_name='Толщина (см)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='monument_width',
            field=models.PositiveIntegerField(blank=True, help_text='Для памятников', null=True, verbose_name='Ширина (см)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tile_length',
            field=models.PositiveIntegerField(blank=True, help_text='Для плитки', null=True, verbose_name='Длина плитки (см)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tile_width',
            field=models.PositiveIntegerField(blank=True, help_text='Для плитки', null=True, verbose_name='Ширина плитки (см)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tiles_per_pack',
            field=models.PositiveIntegerField(blank=True, help_text='Для плитки', null=True, verbose_name='Штук в упаковке'),
        ),
    ]
