# Generated by Django 5.2 on 2026-05-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='coating_type',
            field=models.CharField(blank=True, choices=[('polished', 'Полированная'), ('matte', 'Матовая'), ('brushed', 'Брашированная'), ('thermal', 'Термообработанная'), ('natural', 'Натуральная')], default='', max_length=30, verbose_name='Тип покрытия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, choices=[('granite', 'Гранит'), ('marble', 'Мрамор'), ('limestone', 'Известняк'), ('composite', 'Композит'), ('other', 'Другое')], default='', max_length=20, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='service_notes',
            field=models.TextField(blank=True, default='', verbose_name='Особенности услуги'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
