# Generated by Django 6.0.5 on 2026-05-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_product_coating_type_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fence_pattern_height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Высота рисунка (см)'),
        ),
    ]
