# Generated by Django 6.0.5 on 2026-05-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_product_coating_type_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fence_height_pattern',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Высота рисунка (см)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('product', 'Товар'), ('service', 'Услуга'), ('fence', 'Оградка')], default='product', max_length=10, verbose_name='Тип'),
        ),
    ]
