# Generated by Django 6.0.5 on 2026-05-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_product_fence_height_product_fence_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fence_material',
            field=models.CharField(blank=True, choices=[('metal_profile', 'Металлический профиль'), ('steel_pipe', 'Стальная труба'), ('wrought_iron', 'Кованое железо'), ('aluminum', 'Алюминий'), ('chain_link', 'Сетка рабица'), ('other', 'Другое')], default='', max_length=30, verbose_name='Материал оградки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, choices=[('granite', 'Гранит'), ('marble', 'Мрамор'), ('limestone', 'Известняк'), ('composite', 'Композит'), ('metal', 'Металл'), ('other', 'Другое')], default='', max_length=20, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('product', 'Товар'), ('service', 'Услуга')], default='product', max_length=10, verbose_name='Тип'),
        ),
    ]
