# Generated by Django 6.0.5 on 2026-05-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
