"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k791yr+-3b$*2&b7tfkhjtykga1rpu79(b&s0(2g&4y-wfqz+8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # Jazzmin first for admin customization
    'jazzmin',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Local apps
    'apps.core',
    'apps.goods',
    'apps.news',
    'apps.cart',
    'apps.orders',
    'apps.users',
    
    # Third party
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.core.context_processors.contact_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Fixtures directories
FIXTURE_DIRS = [BASE_DIR / 'fixtures']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'auth.User'

# Jazzmin configuration (бежево-коричневая тема)
JAZZMIN_SETTINGS = {
    "site_title": "Память - Администрирование",
    "site_header": "Память",
    "site_brand": "Интернет-магазин ритуальных услуг",
    "welcome_sign": "Добро пожаловать в панель управления магазином «Память»",
    "copyright": "ООО «Память»",
    "search_model": ["goods.Product", "news.News", "orders.Order"],
    "user_avatar": None,
    
    # Цветовая схема - бежево-коричневая гамма
    "topmenu_color": "#5C4033",
    "sidebar_color": "#8B7355",
    "primary_color": "#8B7355",
    "secondary_color": "#D4C4A8",
    "accent_color": "#5C4033",
    "related_modal_active_color": "#D4C4A8",
    "related_modal_background_color": "#F5F0E8",
    
    # UI настройки
    "navigation_expanded": True,
    "hide_apps": [],
    "order_with_respect_to": [
        "Goods",
        "News",
        "Orders",
        "Cart",
        "Core",
        "Users",
    ],
    "custom_links": {},
    "icons": {
        "goods.category": "fas fa-list",
        "goods.product": "fas fa-box",
        "news.news": "fas fa-newspaper",
        "orders.order": "fas fa-shopping-cart",
        "cart.cart": "fas fa-shopping-basket",
        "core.contactinfo": "fas fa-address-card",
        "core.slider": "fas fa-images",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
    },
    "default_icon_children": "fas fa-circle",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "secondary",
    "adminlte_version": "3.2.0",
    "dark_mode_theme": None,
}
